# FomulaBEAT

変更点
- デコーダのみで学習させる
- TransformerDecoderLayerをスクラッチで書く


In [1]:
version = '03'
model_dir = './model/' + version
data_path = 'data/eq03.txt'

In [2]:
from pathlib import Path
import math
import time
from collections import Counter
from tqdm import tqdm
import torch
from torch.utils.data import random_split
import torch.nn as nn
from torch import Tensor
from torch.nn import (
    TransformerEncoder, TransformerDecoder,
    TransformerEncoderLayer, TransformerDecoderLayer
)
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import vocab
from torchtext.utils import download_from_url, extract_archive
import torch.nn.functional as F


/home/arifuku/ymmtlab/TransformerAnsys/.venv/lib/python3.10/site-packages/torchtext/data/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/home/arifuku/ymmtlab/TransformerAnsys/.venv/lib/python3.10/site-packages/torchtext/vocab/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/home/arifuku/ymmtlab/TransformerAnsys/.venv/lib/python3.10/site-packages/torchte

パラメータの事前設定

In [3]:
%load_ext autoreload
%autoreload 2
torch.set_printoptions(linewidth=100)

In [4]:

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

model_dir_path = Path(model_dir)
if not model_dir_path.exists():
    model_dir_path.mkdir(parents=True)

データの取得

In [5]:
def read_equation_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    src_data, tgt_data = [], []
    for line in lines:
        src, tgt = line.strip().split(' => ')
        src_data.append(src)
        tgt_data.append(tgt)
    return src_data, tgt_data


In [6]:
# ファイルを読み込み、数式データを取得
src_data, tgt_data = read_equation_file(data_path)
print(src_data[:3], tgt_data[:3])


['+ 4 6', '- 3 - 1 + 6 3', '+ 8 7'] ['4 6 +', '3 1 6 3 + - -', '8 7 +']


辞書データの作成

In [7]:

SPECIALS = ['<unk>', '<pad>', '<start>', '<end>']

def build_vocab(texts):
    vocab = {}
    idx = 0
    # 数字の語彙定義
    for i in range(10):
        vocab[str(i)] = idx
        idx += 1
    # 特別語の語彙定義
    for sp in SPECIALS:
        vocab[sp] = idx
        idx += 1
    # その他の文字の語彙定義
    for text in texts:
        for char in text:
            if char not in vocab:
                vocab[char] = idx
                idx += 1
    return vocab


def convert_text_to_indexes(text, vocab):
    # <start> と <end> トークンを追加して数値化
    return [vocab['<start>']] + [vocab[char] if char in vocab else vocab['<unk>'] for char in text] + [vocab['<end>']]

# データを処理して Train と Valid に分ける関数
# データを処理して Train と Valid に分ける関数
def data_process_split(src_texts, tgt_texts, vocab_src, vocab_tgt, valid_size=0.2):
    # データを数値化
    data = []
    for (src, tgt) in zip(src_texts, tgt_texts):
        src_tensor = torch.tensor(convert_text_to_indexes(src, vocab_src), dtype=torch.long)
        tgt_tensor = torch.tensor(convert_text_to_indexes(tgt, vocab_tgt), dtype=torch.long)
        data.append((src_tensor, tgt_tensor))
    
    # データのサイズを計算して、訓練データと検証データに分割
    data_size = len(data)
    valid_size = int(valid_size * data_size)
    train_size = data_size - valid_size

    # PyTorchのrandom_splitを使って分割
    train_data, valid_data = random_split(data, [train_size, valid_size])
    
    return train_data, valid_data



In [8]:
# 辞書と逆辞書を構築
vocab_src = build_vocab(src_data)
vocab_tgt = build_vocab(tgt_data)

print(vocab_tgt)

{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '<unk>': 10, '<pad>': 11, '<start>': 12, '<end>': 13, ' ': 14, '+': 15, '-': 16}


In [9]:

# データを数値化
train_data, valid_data = data_process_split(src_data, tgt_data, vocab_src, vocab_tgt)

# 結果の確認
print('インデックス化された文章')
print(f"Input: {train_data[0][0]}\nOutput: {train_data[0][1]}")

# インデックスから元の文字列に戻す
def convert_indexes_to_text(indexes:list, vocab):
    reverse_vocab = {idx: token for token, idx in vocab.items()}
    return ''.join([reverse_vocab[idx] for idx in indexes if idx in reverse_vocab and reverse_vocab[idx] not in ['<start>', '<end>', '<pad>']])

print('元に戻した文章')
print(f"Input: {convert_indexes_to_text(train_data[0][0].tolist(), vocab_src)}")
print(f"Output: {convert_indexes_to_text(train_data[0][1].tolist(), vocab_tgt)}")


インデックス化された文章
Input: tensor([12, 16, 15,  5, 15, 14, 15, 14, 15,  5, 15,  6, 15,  7, 13])
Output: tensor([12,  5, 14,  5, 14,  6, 14, 15, 14,  7, 14, 15, 14, 16, 13])
元に戻した文章
Input: - 5 + + 5 6 7
Output: 5 5 6 + 7 + -


In [10]:
batch_size = 128
PAD_IDX = vocab_src['<pad>']
START_IDX = vocab_src['<start>']
END_IDX = vocab_src['<end>']

def generate_batch(data_batch):
    
    batch_src, batch_tgt = [], []
    for src, tgt in data_batch:
        batch_src.append(src)
        batch_tgt.append(tgt)
        
    batch_src = pad_sequence(batch_src, padding_value=PAD_IDX)
    batch_tgt = pad_sequence(batch_tgt, padding_value=PAD_IDX)
    
    return batch_src, batch_tgt

train_iter = DataLoader(train_data, batch_size=batch_size, shuffle=True, collate_fn=generate_batch)
valid_iter = DataLoader(valid_data, batch_size=batch_size, shuffle=True, collate_fn=generate_batch)

In [11]:
len(train_data)

80000

Transoformerの設定

In [12]:
class TokenEmbedding(nn.Module):
    
    def __init__(self, vocab_size, embedding_size):
        
        super(TokenEmbedding, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_size, padding_idx=PAD_IDX)
        self.embedding_size = embedding_size
        
    def forward(self, tokens: Tensor):
        return self.embedding(tokens.long()) * math.sqrt(self.embedding_size)
    
    
class PositionalEncoding(nn.Module):
    
    def __init__(self, embedding_size: int, dropout: float, maxlen: int = 5000):
        super(PositionalEncoding, self).__init__()
        
        den = torch.exp(-torch.arange(0, embedding_size, 2) * math.log(10000) / embedding_size)
        pos = torch.arange(0, maxlen).reshape(maxlen, 1)
        embedding_pos = torch.zeros((maxlen, embedding_size))
        embedding_pos[:, 0::2] = torch.sin(pos * den)
        embedding_pos[:, 1::2] = torch.cos(pos * den)
        embedding_pos = embedding_pos.unsqueeze(-2)

        self.dropout = nn.Dropout(dropout)
        self.register_buffer('embedding_pos', embedding_pos)

    def forward(self, token_embedding: Tensor):
        return self.dropout(token_embedding + self.embedding_pos[: token_embedding.size(0), :])


In [13]:

class TransformerDecoderLayerScratch(nn.Module):
    def __init__(self, d_model, nhead, dim_feedforward, dropout=0.1):
        super(TransformerDecoderLayerScratch, self).__init__()
        # Self-attention for the decoder
        self.self_attn = nn.MultiheadAttention(d_model, nhead, dropout=dropout)
        # Multihead attention for attending to encoder outputs (memory)
        self.multihead_attn = nn.MultiheadAttention(d_model, nhead, dropout=dropout)
        # Feedforward layers
        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.dropout = nn.Dropout(dropout)
        self.linear2 = nn.Linear(dim_feedforward, d_model)
        # Layer normalization layers
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.norm3 = nn.LayerNorm(d_model)
        # Dropout
        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)
        self.dropout3 = nn.Dropout(dropout)

    def forward(self, tgt, memory, tgt_mask=None, memory_mask=None, tgt_key_padding_mask=None, memory_key_padding_mask=None):
        # Self-attention
        tgt2, _ = self.self_attn(tgt, tgt, tgt, attn_mask=tgt_mask, key_padding_mask=tgt_key_padding_mask)
        tgt = tgt + self.dropout1(tgt2)
        tgt = self.norm1(tgt)
        
        # Attention with the encoder outputs (memory)
        tgt2, _ = self.multihead_attn(tgt, memory, memory, attn_mask=memory_mask, key_padding_mask=memory_key_padding_mask)
        tgt = tgt + self.dropout2(tgt2)
        tgt = self.norm2(tgt)
        
        # Feedforward network
        tgt2 = self.linear2(self.dropout(F.relu(self.linear1(tgt))))
        tgt = tgt + self.dropout3(tgt2)
        tgt = self.norm3(tgt)

        return tgt


In [14]:

class Seq2SeqTransformer(nn.Module):
    
    def __init__(
        self, num_encoder_layers: int, num_decoder_layers: int,
        embedding_size: int, vocab_size_src: int, vocab_size_tgt: int,
        dim_feedforward:int = 512, dropout:float = 0.1, nhead:int = 8
    ):
        
        super(Seq2SeqTransformer, self).__init__()

        self.token_embedding_src = TokenEmbedding(vocab_size_src, embedding_size)
        self.positional_encoding = PositionalEncoding(embedding_size, dropout=dropout)
        
        self.token_embedding_tgt = TokenEmbedding(vocab_size_tgt, embedding_size)
        self.decoder_layer = TransformerDecoderLayerScratch(
            d_model=embedding_size, nhead=nhead, dim_feedforward=dim_feedforward, dropout=dropout
        )
        
        self.output = nn.Linear(embedding_size, vocab_size_tgt)

    def forward(
        self, src: Tensor, tgt: Tensor,
        mask_src: Tensor, mask_tgt: Tensor,
        padding_mask_src: Tensor, padding_mask_tgt: Tensor,
        memory_key_padding_mask: Tensor
    ):
        embedding_src = self.positional_encoding(self.token_embedding_src(src))
        # memory = self.transformer_encoder(embedding_src, mask_src, padding_mask_src)
        embedding_tgt = self.positional_encoding(self.token_embedding_tgt(tgt))
        outs = self.decoder_layer(
            embedding_tgt, embedding_src, mask_tgt, None,
            padding_mask_tgt, memory_key_padding_mask
        )
        return self.output(outs)

    def decode(self, tgt: Tensor, memory: Tensor, mask_tgt: Tensor):
        return self.decoder_layer(self.positional_encoding(self.token_embedding_tgt(tgt)), memory, mask_tgt)

In [15]:
def create_mask(src, tgt, PAD_IDX):
    
    seq_len_src = src.shape[0]
    seq_len_tgt = tgt.shape[0]

    mask_src = torch.zeros((seq_len_src, seq_len_src), device=device).type(torch.bool)
    mask_tgt = generate_square_subsequent_mask(seq_len_tgt)

    padding_mask_src = (src == PAD_IDX).transpose(0, 1)
    padding_mask_tgt = (tgt == PAD_IDX).transpose(0, 1)
    
    return mask_src, mask_tgt, padding_mask_src, padding_mask_tgt


def generate_square_subsequent_mask(seq_len):
    mask = (torch.triu(torch.ones((seq_len, seq_len), device=device)) == 1).transpose(0, 1)
    mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
    return mask

学習の定義

In [16]:
def train(model, data, optimizer, criterion, PAD_IDX):
    
    model.train()
    losses = 0
    for src, tgt in tqdm(data):
        
        src = src.to(device)
        tgt = tgt.to(device)

        input_tgt = tgt[:-1, :]

        mask_src, mask_tgt, padding_mask_src, padding_mask_tgt = create_mask(src, input_tgt, PAD_IDX)

        logits = model(
            src=src, tgt=input_tgt,
            mask_src=mask_src, mask_tgt=mask_tgt,
            padding_mask_src=padding_mask_src, padding_mask_tgt=padding_mask_tgt,
            memory_key_padding_mask=padding_mask_src
        )

        optimizer.zero_grad()
        output_tgt = tgt[1:, :]
        loss = criterion(logits.reshape(-1, logits.shape[-1]), output_tgt.reshape(-1))
        loss.backward()

        optimizer.step()
        losses += loss.item()
        
    return losses / len(data)

In [17]:

def evaluate(model, data, criterion, PAD_IDX):
    
    model.eval()
    losses = 0
    for src, tgt in data:
        
        src = src.to(device)
        tgt = tgt.to(device)

        input_tgt = tgt[:-1, :]

        mask_src, mask_tgt, padding_mask_src, padding_mask_tgt = create_mask(src, input_tgt, PAD_IDX)

        logits = model(
            src=src, tgt=input_tgt,
            mask_src=mask_src, mask_tgt=mask_tgt,
            padding_mask_src=padding_mask_src, padding_mask_tgt=padding_mask_tgt,
            memory_key_padding_mask=padding_mask_src
        )
        
        output_tgt = tgt[1:, :]
        loss = criterion(logits.reshape(-1, logits.shape[-1]), output_tgt.reshape(-1))
        losses += loss.item()
        
    return losses / len(data)

設定

In [18]:
vocab_size_src = len(vocab_src)
vocab_size_tgt = len(vocab_tgt)
embedding_size = 4
nhead = 1
dim_feedforward = 4
num_encoder_layers = 1
num_decoder_layers = 1
dropout = 0
# vocab_size_src = len(vocab_src)
# vocab_size_tgt = len(vocab_tgt)
# embedding_size = 240
# nhead = 8
# dim_feedforward = 100
# num_encoder_layers = 2
# num_decoder_layers = 2
# dropout = 0.1

model = Seq2SeqTransformer(
    num_encoder_layers=num_encoder_layers,
    num_decoder_layers=num_decoder_layers,
    embedding_size=embedding_size,
    vocab_size_src=vocab_size_src, vocab_size_tgt=vocab_size_tgt,
    dim_feedforward=dim_feedforward,
    dropout=dropout, nhead=nhead
)

for p in model.parameters():
    if p.dim() > 1:
        nn.init.xavier_uniform_(p)

model = model.to(device)

criterion = torch.nn.CrossEntropyLoss(ignore_index=PAD_IDX)

optimizer = torch.optim.Adam(model.parameters())

モデルの調査

In [19]:
print(model)

Seq2SeqTransformer(
  (token_embedding_src): TokenEmbedding(
    (embedding): Embedding(17, 4, padding_idx=11)
  )
  (positional_encoding): PositionalEncoding(
    (dropout): Dropout(p=0, inplace=False)
  )
  (token_embedding_tgt): TokenEmbedding(
    (embedding): Embedding(17, 4, padding_idx=11)
  )
  (decoder_layer): TransformerDecoderLayerScratch(
    (self_attn): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
    )
    (multihead_attn): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
    )
    (linear1): Linear(in_features=4, out_features=4, bias=True)
    (dropout): Dropout(p=0, inplace=False)
    (linear2): Linear(in_features=4, out_features=4, bias=True)
    (norm1): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
    (norm2): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
    (norm3): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
    (d

In [20]:
# モデル内の層の名前とパラメータ情報を表示
LP = list(model.named_parameters())
lp = len(LP)
print(f"{lp} 層")
for p in range(0, lp):
    print(f"\n層名: {LP[p][0]}")
    print(f"形状: {LP[p][1].shape}")
    print(f"値: {LP[p][1]}")


22 層

層名: token_embedding_src.embedding.weight
形状: torch.Size([17, 4])
値: Parameter containing:
tensor([[-0.1556,  0.3227, -0.3112, -0.1144],
        [ 0.0189,  0.3038, -0.3842, -0.2972],
        [ 0.4724, -0.3318,  0.0431,  0.0655],
        [-0.2612, -0.1869, -0.4495,  0.0242],
        [-0.4885,  0.1143,  0.3369,  0.3918],
        [-0.4730, -0.2358, -0.5093, -0.1757],
        [-0.1245, -0.3616, -0.1465, -0.2224],
        [ 0.0900, -0.0809, -0.4698,  0.0967],
        [-0.1259,  0.0021,  0.1130, -0.3577],
        [ 0.0074,  0.1421,  0.3809,  0.5034],
        [-0.4569, -0.1839,  0.0345, -0.4492],
        [-0.3190, -0.0924, -0.5344, -0.2240],
        [ 0.0706, -0.4735,  0.3436, -0.4156],
        [ 0.2067,  0.3581, -0.2850,  0.3873],
        [-0.0940,  0.2464,  0.2866, -0.2950],
        [-0.3049, -0.0253, -0.0247,  0.3094],
        [-0.1551, -0.2533, -0.2452, -0.4308]], device='cuda:0', requires_grad=True)

層名: token_embedding_tgt.embedding.weight
形状: torch.Size([17, 4])
値: Parameter conta

## 学習実行

In [21]:
epoch = 100
best_loss = float('Inf')
best_model = None
patience = 10
counter = 0

for loop in range(1, epoch + 1):
    
    start_time = time.time()
    
    loss_train = train(
        model=model, data=train_iter, optimizer=optimizer,
        criterion=criterion, PAD_IDX=PAD_IDX
    )
    
    elapsed_time = time.time() - start_time
    
    loss_valid = evaluate(
        model=model, data=valid_iter, criterion=criterion, PAD_IDX=PAD_IDX
    )
    
    print('[{}/{}] train loss: {:.2f}, valid loss: {:.2f}  [{}{:.0f}s] counter: {} {}'.format(
        loop, epoch,
        loss_train, loss_valid,
        str(int(math.floor(elapsed_time / 60))) + 'm' if math.floor(elapsed_time / 60) > 0 else '',
        elapsed_time % 60,
        counter,
        '**' if best_loss > loss_valid else ''
    ))
    
    if best_loss > loss_valid:
        best_loss = loss_valid
        best_model = model
        counter = 0
        
    if counter > patience:
        break
    
    counter += 1

  0%|          | 0/625 [00:00<?, ?it/s]/home/arifuku/ymmtlab/TransformerAnsys/.venv/lib/python3.10/site-packages/torch/nn/functional.py:5137: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(
100%|██████████| 625/625 [00:08<00:00, 74.50it/s]


[1/100] train loss: 2.01, valid loss: 1.29  [8s] counter: 0 **


100%|██████████| 625/625 [00:08<00:00, 76.43it/s]


[2/100] train loss: 1.01, valid loss: 0.84  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 76.27it/s]


[3/100] train loss: 0.79, valid loss: 0.75  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 77.05it/s]


[4/100] train loss: 0.72, valid loss: 0.70  [8s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 201.94it/s]


[5/100] train loss: 0.68, valid loss: 0.66  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 201.91it/s]


[6/100] train loss: 0.64, valid loss: 0.62  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 201.83it/s]


[7/100] train loss: 0.60, valid loss: 0.59  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 201.89it/s]


[8/100] train loss: 0.57, valid loss: 0.56  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 202.04it/s]


[9/100] train loss: 0.55, valid loss: 0.55  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 202.21it/s]


[10/100] train loss: 0.54, valid loss: 0.54  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 202.08it/s]


[11/100] train loss: 0.55, valid loss: 0.53  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 201.87it/s]


[12/100] train loss: 0.56, valid loss: 0.53  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 202.01it/s]


[13/100] train loss: 0.54, valid loss: 0.52  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 201.64it/s]


[14/100] train loss: 0.57, valid loss: 0.52  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 201.96it/s]


[15/100] train loss: 0.53, valid loss: 0.52  [3s] counter: 1 **


100%|██████████| 625/625 [00:03<00:00, 202.05it/s]


[16/100] train loss: 0.59, valid loss: 0.67  [3s] counter: 1 


100%|██████████| 625/625 [00:04<00:00, 144.74it/s]


[17/100] train loss: 0.55, valid loss: 0.52  [4s] counter: 2 **


100%|██████████| 625/625 [00:08<00:00, 77.76it/s]


[18/100] train loss: 0.54, valid loss: 0.51  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 77.01it/s]


[19/100] train loss: 0.55, valid loss: 0.51  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 76.82it/s]


[20/100] train loss: 0.55, valid loss: 0.51  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 77.75it/s]


[21/100] train loss: 0.51, valid loss: 0.51  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 76.54it/s]


[22/100] train loss: 0.55, valid loss: 0.52  [8s] counter: 3 


100%|██████████| 625/625 [00:08<00:00, 76.68it/s]


[23/100] train loss: 0.51, valid loss: 0.68  [8s] counter: 4 


100%|██████████| 625/625 [00:08<00:00, 76.84it/s]


[24/100] train loss: 0.56, valid loss: 0.62  [8s] counter: 5 


100%|██████████| 625/625 [00:08<00:00, 77.82it/s]


[25/100] train loss: 0.53, valid loss: 0.51  [8s] counter: 6 **


100%|██████████| 625/625 [00:08<00:00, 76.81it/s]


[26/100] train loss: 0.51, valid loss: 0.50  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 76.99it/s]


[27/100] train loss: 0.54, valid loss: 0.50  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 77.26it/s]


[28/100] train loss: 0.53, valid loss: 0.50  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 76.55it/s]


[29/100] train loss: 0.50, valid loss: 0.50  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 76.65it/s]


[30/100] train loss: 0.50, valid loss: 0.50  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 76.75it/s]


[31/100] train loss: 0.53, valid loss: 0.55  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 77.30it/s]


[32/100] train loss: 0.51, valid loss: 0.50  [8s] counter: 3 


100%|██████████| 625/625 [00:08<00:00, 76.72it/s]


[33/100] train loss: 0.51, valid loss: 0.50  [8s] counter: 4 **


100%|██████████| 625/625 [00:08<00:00, 77.01it/s]


[34/100] train loss: 0.54, valid loss: 0.50  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 77.39it/s]


[35/100] train loss: 0.56, valid loss: 0.55  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 76.65it/s]


[36/100] train loss: 0.55, valid loss: 0.58  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 76.92it/s]


[37/100] train loss: 0.56, valid loss: 0.54  [8s] counter: 3 


100%|██████████| 625/625 [00:08<00:00, 77.77it/s]


[38/100] train loss: 0.53, valid loss: 0.52  [8s] counter: 4 


100%|██████████| 625/625 [00:08<00:00, 76.94it/s]


[39/100] train loss: 0.58, valid loss: 0.56  [8s] counter: 5 


100%|██████████| 625/625 [00:08<00:00, 76.86it/s]


[40/100] train loss: 0.55, valid loss: 0.53  [8s] counter: 6 


100%|██████████| 625/625 [00:08<00:00, 77.31it/s]


[41/100] train loss: 0.52, valid loss: 0.52  [8s] counter: 7 


100%|██████████| 625/625 [00:08<00:00, 77.32it/s]


[42/100] train loss: 0.54, valid loss: 0.51  [8s] counter: 8 


100%|██████████| 625/625 [00:08<00:00, 77.24it/s]


[43/100] train loss: 0.54, valid loss: 0.50  [8s] counter: 9 


100%|██████████| 625/625 [00:08<00:00, 77.44it/s]


[44/100] train loss: 0.52, valid loss: 0.50  [8s] counter: 10 **


100%|██████████| 625/625 [00:08<00:00, 77.79it/s]


[45/100] train loss: 0.50, valid loss: 0.64  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 77.19it/s]


[46/100] train loss: 0.52, valid loss: 0.49  [8s] counter: 2 **


100%|██████████| 625/625 [00:08<00:00, 76.73it/s]


[47/100] train loss: 0.52, valid loss: 0.50  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 76.67it/s]


[48/100] train loss: 0.52, valid loss: 0.57  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 76.75it/s]


[49/100] train loss: 0.49, valid loss: 0.49  [8s] counter: 3 **


100%|██████████| 625/625 [00:08<00:00, 76.56it/s]


[50/100] train loss: 0.52, valid loss: 0.49  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 77.64it/s]


[51/100] train loss: 0.54, valid loss: 0.49  [8s] counter: 1 


100%|██████████| 625/625 [00:07<00:00, 79.08it/s]


[52/100] train loss: 0.52, valid loss: 0.49  [8s] counter: 2 **


100%|██████████| 625/625 [00:07<00:00, 78.15it/s]


[53/100] train loss: 0.50, valid loss: 0.49  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 78.08it/s]


[54/100] train loss: 0.49, valid loss: 0.48  [8s] counter: 2 **


100%|██████████| 625/625 [00:08<00:00, 77.33it/s]


[55/100] train loss: 0.57, valid loss: 0.56  [8s] counter: 1 


100%|██████████| 625/625 [00:07<00:00, 79.81it/s]


[56/100] train loss: 0.55, valid loss: 0.59  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 75.58it/s]


[57/100] train loss: 0.52, valid loss: 0.49  [8s] counter: 3 


100%|██████████| 625/625 [00:08<00:00, 76.73it/s]


[58/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 4 


100%|██████████| 625/625 [00:08<00:00, 76.59it/s]


[59/100] train loss: 0.51, valid loss: 0.49  [8s] counter: 5 


100%|██████████| 625/625 [00:08<00:00, 76.90it/s]


[60/100] train loss: 0.52, valid loss: 0.50  [8s] counter: 6 


100%|██████████| 625/625 [00:08<00:00, 77.10it/s]


[61/100] train loss: 0.51, valid loss: 0.55  [8s] counter: 7 


100%|██████████| 625/625 [00:08<00:00, 76.11it/s]


[62/100] train loss: 0.50, valid loss: 0.56  [8s] counter: 8 


100%|██████████| 625/625 [00:08<00:00, 76.11it/s]


[63/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 9 **


100%|██████████| 625/625 [00:08<00:00, 77.09it/s]


[64/100] train loss: 0.49, valid loss: 0.48  [8s] counter: 1 **


100%|██████████| 625/625 [00:07<00:00, 79.62it/s]


[65/100] train loss: 0.52, valid loss: 0.48  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 76.41it/s]


[66/100] train loss: 0.49, valid loss: 0.60  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 76.52it/s]


[67/100] train loss: 0.49, valid loss: 0.48  [8s] counter: 3 **


100%|██████████| 625/625 [00:08<00:00, 76.74it/s]


[68/100] train loss: 0.49, valid loss: 0.59  [8s] counter: 1 


100%|██████████| 625/625 [00:07<00:00, 79.45it/s]


[69/100] train loss: 0.50, valid loss: 0.59  [8s] counter: 2 


100%|██████████| 625/625 [00:07<00:00, 79.55it/s]


[70/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 3 **


100%|██████████| 625/625 [00:08<00:00, 78.10it/s]


[71/100] train loss: 0.52, valid loss: 0.48  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 76.11it/s]


[72/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 76.41it/s]


[73/100] train loss: 0.53, valid loss: 0.48  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 76.67it/s]


[74/100] train loss: 0.53, valid loss: 0.48  [8s] counter: 3 


100%|██████████| 625/625 [00:08<00:00, 76.21it/s]


[75/100] train loss: 0.49, valid loss: 0.55  [8s] counter: 4 


100%|██████████| 625/625 [00:08<00:00, 76.14it/s]


[76/100] train loss: 0.57, valid loss: 0.57  [8s] counter: 5 


100%|██████████| 625/625 [00:08<00:00, 76.27it/s]


[77/100] train loss: 0.53, valid loss: 0.50  [8s] counter: 6 


100%|██████████| 625/625 [00:08<00:00, 77.00it/s]


[78/100] train loss: 0.50, valid loss: 0.53  [8s] counter: 7 


100%|██████████| 625/625 [00:08<00:00, 76.35it/s]


[79/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 8 


100%|██████████| 625/625 [00:08<00:00, 76.22it/s]


[80/100] train loss: 0.49, valid loss: 0.50  [8s] counter: 9 


100%|██████████| 625/625 [00:08<00:00, 76.98it/s]


[81/100] train loss: 0.48, valid loss: 0.48  [8s] counter: 10 **


100%|██████████| 625/625 [00:08<00:00, 76.58it/s]


[82/100] train loss: 0.48, valid loss: 0.47  [8s] counter: 1 **


100%|██████████| 625/625 [00:08<00:00, 76.56it/s]


[83/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 76.48it/s]


[84/100] train loss: 0.48, valid loss: 0.58  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 77.18it/s]


[85/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 3 


100%|██████████| 625/625 [00:08<00:00, 76.52it/s]


[86/100] train loss: 0.52, valid loss: 0.63  [8s] counter: 4 


100%|██████████| 625/625 [00:08<00:00, 76.53it/s]


[87/100] train loss: 0.52, valid loss: 0.48  [8s] counter: 5 


100%|██████████| 625/625 [00:08<00:00, 77.24it/s]


[88/100] train loss: 0.49, valid loss: 0.54  [8s] counter: 6 


100%|██████████| 625/625 [00:08<00:00, 76.48it/s]


[89/100] train loss: 0.48, valid loss: 0.47  [8s] counter: 7 **


100%|██████████| 625/625 [00:08<00:00, 76.67it/s]


[90/100] train loss: 0.48, valid loss: 0.47  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 76.67it/s]


[91/100] train loss: 0.54, valid loss: 0.50  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 76.85it/s]


[92/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 3 


100%|██████████| 625/625 [00:08<00:00, 76.38it/s]


[93/100] train loss: 0.51, valid loss: 0.47  [8s] counter: 4 **


100%|██████████| 625/625 [00:08<00:00, 76.58it/s]


[94/100] train loss: 0.54, valid loss: 0.47  [8s] counter: 1 


100%|██████████| 625/625 [00:08<00:00, 77.14it/s]


[95/100] train loss: 0.50, valid loss: 0.48  [8s] counter: 2 


100%|██████████| 625/625 [00:08<00:00, 76.78it/s]


[96/100] train loss: 0.50, valid loss: 0.62  [8s] counter: 3 


100%|██████████| 625/625 [00:05<00:00, 122.35it/s]


[97/100] train loss: 0.53, valid loss: 0.48  [5s] counter: 4 


100%|██████████| 625/625 [00:03<00:00, 200.59it/s]


[98/100] train loss: 0.48, valid loss: 0.48  [3s] counter: 5 


100%|██████████| 625/625 [00:03<00:00, 199.31it/s]


[99/100] train loss: 0.47, valid loss: 0.49  [3s] counter: 6 


100%|██████████| 625/625 [00:03<00:00, 201.23it/s]


[100/100] train loss: 0.51, valid loss: 0.47  [3s] counter: 7 **


学習したモデルの保存

In [49]:
torch.save(best_model.state_dict(), model_dir_path.joinpath(version + 'translation_transfomer.pth'))

学習したモデルを使って翻訳をする

In [50]:
def translate(
    model, text, vocab_src, vocab_tgt, seq_len_tgt,
    START_IDX, END_IDX
):
    model.eval()
    tokens_src = convert_text_to_indexes(text, vocab=vocab_src)
    num_tokens_src = len(tokens_src)

    # Tensorに変換
    src = torch.LongTensor(tokens_src).reshape(num_tokens_src, 1).to(device)
    mask_src = torch.zeros((num_tokens_src, num_tokens_src), device=device).type(torch.bool)

    # デコード
    predicts = greedy_decode(
        model=model, src=src,
        mask_src=mask_src, seq_len_tgt=seq_len_tgt,
        START_IDX=START_IDX, END_IDX=END_IDX
    ).flatten()

    return convert_indexes_to_text(predicts.tolist(), vocab=vocab_tgt)

def greedy_decode(model, src, mask_src, seq_len_tgt, START_IDX, END_IDX):
    src = src.to(device)
    mask_src = mask_src.to(device)

    # ソースの埋め込みをメモリとして利用
    memory = model.positional_encoding(model.token_embedding_src(src))
    
    ys = torch.ones(1, 1).fill_(START_IDX).type(torch.long).to(device)
    
    for i in range(seq_len_tgt - 1):
        memory = memory.to(device)
        mask_tgt = generate_square_subsequent_mask(ys.size(0)).to(device).type(torch.bool)
        
        output = model.decode(ys, memory, mask_tgt)
        output = output.transpose(0, 1)
        output = model.output(output[:, -1])
        
        # 最も高いスコアのトークンを取得
        _, next_word = torch.max(output, dim=1)
        next_word = next_word.item()

        # 生成されたトークンを追加
        ys = torch.cat([ys, torch.ones(1, 1).fill_(next_word).type_as(src.data)], dim=0)
        if next_word == END_IDX:
            break
    
    return ys


In [51]:
seq_len_tgt = max([len(x[1]) for x in train_data])
text = '- 5 2'

# 翻訳を実行
translation = translate(
    model=best_model, text=text, vocab_src=vocab_src, vocab_tgt=vocab_tgt,
    seq_len_tgt=seq_len_tgt,
    START_IDX=START_IDX, END_IDX=END_IDX
)

print(f"Input: {text}")
print(f"Output: {translation}")

Input: - 5 2
Output: 5 2 -


In [52]:
# 様々な入力を試してみる

text_list = { '- 2 7':'2 7 -', '- 9 7' : '9 7 -', '+ - 2 7 4' : '2 7 - 4 +', '- - 6 9 - 7 3' : '6 9 - 7 3 - -', '- - + + + + + 4 6 3 7 + 6 7 1 9 + + 3 6 2' : '4 6 + 3 + 7 + 6 7 + + 1 + 9 - 3 6 + 2 + - '}

for text, tgt in text_list.items():
    translation = translate(
        model=best_model, text=text, vocab_src=vocab_src, vocab_tgt=vocab_tgt,
        seq_len_tgt=seq_len_tgt,
        START_IDX=START_IDX, END_IDX=END_IDX
    )
    print(f"Input: {text}")
    print(f"Output: {translation}")
    print(f"Target: {tgt}")
    print('---')




Input: - 2 7
Output: 2 7 -
Target: 2 7 -
---
Input: - 9 7
Output: 9 7 -
Target: 9 7 -
---
Input: + - 2 7 4
Output: 6 5 + 3 +
Target: 2 7 - 4 +
---
Input: - - 6 9 - 7 3
Output: 4 6 - 3 - - 3 - - -
Target: 6 9 - 7 3 - -
---
Input: - - + + + + + 4 6 3 7 + 6 7 1 9 + + 3 6 2
Output: 6 6 4 + + 3 + + 4 + + + + 9 + + 4 + + 4 + + 9 + + + + + + + + + + + + 
Target: 4 6 + 3 + 7 + 6 7 + + 1 + 9 - 3 6 + 2 + - 
---


## モデルの動作を分析

In [126]:
import torch

# モデルのロード
model_path = model_dir_path.joinpath(version + 'translation_transfomer.pth')
loaded_model = Seq2SeqTransformer(
    num_encoder_layers=num_encoder_layers,
    num_decoder_layers=num_decoder_layers,
    embedding_size=embedding_size,
    vocab_size_src=vocab_size_src, vocab_size_tgt=vocab_size_tgt,
    dim_feedforward=dim_feedforward,
    dropout=dropout, nhead=nhead
).to(device)
loaded_model.load_state_dict(torch.load(model_path))
loaded_model.eval()


Seq2SeqTransformer(
  (token_embedding_src): TokenEmbedding(
    (embedding): Embedding(17, 4, padding_idx=11)
  )
  (positional_encoding): PositionalEncoding(
    (dropout): Dropout(p=0, inplace=False)
  )
  (token_embedding_tgt): TokenEmbedding(
    (embedding): Embedding(17, 4, padding_idx=11)
  )
  (decoder_layer): TransformerDecoderLayerScratch(
    (self_attn): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
    )
    (multihead_attn): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
    )
    (linear1): Linear(in_features=4, out_features=4, bias=True)
    (dropout): Dropout(p=0, inplace=False)
    (linear2): Linear(in_features=4, out_features=4, bias=True)
    (norm1): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
    (norm2): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
    (norm3): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
    (d

In [127]:
# パラメータを取り出す


# モデルのパラメータを取得
params = dict(loaded_model.named_parameters())
print(params.keys())

# 埋め込み行列を取得
embedding_src_weight = params['token_embedding_src.embedding.weight'].data
embedding_tgt_weight = params['token_embedding_tgt.embedding.weight'].data

# 線形層の重みとバイアス
output_weight = params['output.weight'].data
output_bias = params['output.bias'].data

# デコーダの自己注意の重みとバイアス
self_attn_in_proj_weight = params['decoder_layer.self_attn.in_proj_weight'].data
self_attn_in_proj_bias = params['decoder_layer.self_attn.in_proj_bias'].data
self_attn_out_proj_weight = params['decoder_layer.self_attn.out_proj.weight'].data
self_attn_out_proj_bias = params['decoder_layer.self_attn.out_proj.bias'].data

# メモリー注意の重みとバイアス
multihead_attn_in_proj_weight = params['decoder_layer.multihead_attn.in_proj_weight'].data
multihead_attn_in_proj_bias = params['decoder_layer.multihead_attn.in_proj_bias'].data
multihead_attn_out_proj_weight = params['decoder_layer.multihead_attn.out_proj.weight'].data
multihead_attn_out_proj_bias = params['decoder_layer.multihead_attn.out_proj.bias'].data

# フィードフォワードネットワークの重みとバイアス
linear1_weight = params['decoder_layer.linear1.weight'].data
linear1_bias = params['decoder_layer.linear1.bias'].data
linear2_weight = params['decoder_layer.linear2.weight'].data
linear2_bias = params['decoder_layer.linear2.bias'].data

# LayerNormのパラメータ
norm1_weight = params['decoder_layer.norm1.weight'].data
norm1_bias = params['decoder_layer.norm1.bias'].data
norm2_weight = params['decoder_layer.norm2.weight'].data
norm2_bias = params['decoder_layer.norm2.bias'].data
norm3_weight = params['decoder_layer.norm3.weight'].data
norm3_bias = params['decoder_layer.norm3.bias'].data


dict_keys(['token_embedding_src.embedding.weight', 'token_embedding_tgt.embedding.weight', 'decoder_layer.self_attn.in_proj_weight', 'decoder_layer.self_attn.in_proj_bias', 'decoder_layer.self_attn.out_proj.weight', 'decoder_layer.self_attn.out_proj.bias', 'decoder_layer.multihead_attn.in_proj_weight', 'decoder_layer.multihead_attn.in_proj_bias', 'decoder_layer.multihead_attn.out_proj.weight', 'decoder_layer.multihead_attn.out_proj.bias', 'decoder_layer.linear1.weight', 'decoder_layer.linear1.bias', 'decoder_layer.linear2.weight', 'decoder_layer.linear2.bias', 'decoder_layer.norm1.weight', 'decoder_layer.norm1.bias', 'decoder_layer.norm2.weight', 'decoder_layer.norm2.bias', 'decoder_layer.norm3.weight', 'decoder_layer.norm3.bias', 'output.weight', 'output.bias'])


In [128]:

# Positional Encoding
def positional_encoding(tensor: Tensor, maxlen=5000):
    embedding_size = tensor.size(-1)
    den = torch.exp(-torch.arange(0, embedding_size, 2) * math.log(10000) / embedding_size)
    pos = torch.arange(0, maxlen).reshape(maxlen, 1)
    embedding_pos = torch.zeros((maxlen, embedding_size))
    embedding_pos[:, 0::2] = torch.sin(pos * den)
    embedding_pos[:, 1::2] = torch.cos(pos * den)
    embedding_pos = embedding_pos.unsqueeze(-2)
    return tensor + embedding_pos[: tensor.size(0), :].to(tensor.device)

In [203]:

# 翻訳処理を実行
seq_len_tgt = max([len(x[1]) for x in train_data])
text = '+ 3 1'

tokens_src = convert_text_to_indexes(text, vocab=vocab_src)
src = torch.LongTensor(tokens_src).reshape(len(tokens_src), 1).to(device)
memory = positional_encoding(embedding_src_weight[src] * math.sqrt(embedding_size))
ys = torch.ones(1, 1).fill_(START_IDX).type(torch.long).to(device)

for i in range(10):
    tgt_embed = positional_encoding(embedding_tgt_weight[ys] * math.sqrt(embedding_size))
    tgt_mask = generate_square_subsequent_mask(ys.size(0)).to(device).type(torch.bool)
    
    # Self-attention
    self_attn_wq, self_attn_wk, self_attn_wv = self_attn_in_proj_weight.chunk(3, dim=0)
    self_attn_bq, self_attn_bk, self_attn_bv = self_attn_in_proj_bias.chunk(3, dim=0)
    QW = torch.matmul(tgt_embed.permute(1, 0, 2), self_attn_wq.T) + self_attn_bq
    KW = torch.matmul(tgt_embed.permute(1, 0, 2), self_attn_wk.T) + self_attn_bk
    VW = torch.matmul(tgt_embed.permute(1, 0, 2), self_attn_wv.T) + self_attn_bv
    self_attn_weights = F.softmax(torch.bmm(QW, KW.transpose(-2, -1)) / math.sqrt(embedding_size), dim=-1)

    AV = torch.matmul(self_attn_weights, VW)
    self_attn_output = torch.matmul(AV, self_attn_out_proj_weight.T) + self_attn_out_proj_bias
    self_attn_output = self_attn_output.permute(1, 0, 2)
    tgt = tgt_embed + self_attn_output
    tgt = loaded_model.decoder_layer.norm1(tgt)



    # Attention with the encoder outputs (memory)
    multi_attn_wq, multi_attn_wk, multi_attn_wv = multihead_attn_in_proj_weight.chunk(3, dim=0)
    multi_attn_bq, multi_attn_bk, multi_attn_bv = multihead_attn_in_proj_bias.chunk(3, dim=0)
    QW = torch.matmul(tgt.permute(1, 0, 2), multi_attn_wq.T) + multi_attn_bq
    KW = torch.matmul(memory.permute(1, 0, 2), multi_attn_wk.T) + multi_attn_bk
    VW = torch.matmul(memory.permute(1, 0, 2), multi_attn_wv.T) + multi_attn_bv
    multi_attn_weights = F.softmax(torch.bmm(QW, KW.transpose(-2, -1)) / math.sqrt(embedding_size), dim=-1)

    AV = torch.matmul(multi_attn_weights, VW)
    multi_attn_output = torch.matmul(AV, multihead_attn_out_proj_weight.T) + multihead_attn_out_proj_bias
    multi_attn_output = multi_attn_output.permute(1, 0, 2)
    tgt = tgt + multi_attn_output
    tgt = loaded_model.decoder_layer.norm2(tgt)
    
    # Feedforward network

    # decoder linear1, 2
    tgt2 = tgt.matmul(linear1_weight.T) + linear1_bias
    tgt2 = F.relu(tgt2)
    tgt2 = tgt2.matmul(linear2_weight.T) + linear2_bias
    tgt = tgt + tgt2

    # LayerNorm
    tgt = loaded_model.decoder_layer.norm3(tgt)

    output = tgt.transpose(0, 1)
    output = loaded_model.output(output[:, -1])

    _, next_word = torch.max(output, dim=1)
    next_word = next_word.item()

    ys = torch.cat([ys, torch.ones(1, 1).fill_(next_word).type_as(src.data)], dim=0)
    print(next_word)
    
    if next_word == END_IDX:
        break


flat_indexes = [idx for sublist in ys.tolist() for idx in sublist] if isinstance(ys.tolist()[0], list) else ys.tolist()

print(f"Input: {text}")
print(f"Decoded sequence: {convert_indexes_to_text(flat_indexes, vocab_tgt)}")

3
14
1
14
15
13
Input: + 3 1
Decoded sequence: 3 1 +


# Transformerの検算

スクラッチで書くための検算

## Multihead Attention

Multihead Attentionの動作をスクラッチで書きたいので、ここで検算する

参考サイト
https://blog.amedama.jp/entry/pytorch-multi-head-attention-verify

In [161]:
import torch
from torch import nn
import torch.nn.functional as F


In [168]:
edim = 4 # 埋め込み次元
num_heads = 1 # ヘッド数
model = nn.MultiheadAttention(edim, num_heads, bias=True)

In [176]:
batch_size = 1
L=5
X = torch.randn(batch_size, 1, edim) # 入力
Y = torch.randn(7, 1, edim) # 出力
print("X:", X.shape)
print("Y:", Y.shape)

X: torch.Size([1, 1, 4])
Y: torch.Size([7, 1, 4])


In [178]:
attn_output, attn_output_weights = model(X, Y, Y)

print(attn_output.shape)
print(attn_output)
print(attn_output_weights)

torch.Size([1, 1, 4])
tensor([[[-0.3499, -0.2916, -0.3890, -0.2463]]], grad_fn=<ViewBackward0>)
tensor([[[0.1734, 0.1847, 0.1077, 0.1364, 0.2069, 0.1434, 0.0475]]], grad_fn=<MeanBackward1>)


In [121]:
from pprint import pprint
pprint(list(model.named_parameters()))

[('in_proj_weight',
  Parameter containing:
tensor([[-0.5630, -0.2601, -0.1945, -0.5896],
        [-0.4404, -0.4852,  0.0115, -0.5999],
        [-0.1480, -0.3680,  0.5783,  0.3258],
        [ 0.1237,  0.1261,  0.5127,  0.4791],
        [-0.5049, -0.2961,  0.1912,  0.4764],
        [ 0.0325, -0.2752, -0.3576, -0.1833],
        [ 0.4593, -0.1369, -0.0845, -0.2567],
        [-0.4142, -0.3853,  0.3486, -0.1582],
        [ 0.1128, -0.1040, -0.0759, -0.5081],
        [-0.5086, -0.5566,  0.2522, -0.4853],
        [ 0.3230, -0.1686,  0.4186,  0.3168],
        [-0.0464,  0.4538,  0.1423, -0.0617]], requires_grad=True)),
 ('in_proj_bias',
  Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)),
 ('out_proj.weight',
  Parameter containing:
tensor([[-0.4730,  0.0490, -0.0549,  0.3015],
        [-0.4261,  0.2245, -0.0424,  0.2772],
        [ 0.3448,  0.4979, -0.0949,  0.0385],
        [-0.4854,  0.3669,  0.0725, -0.3572]], requires_grad=True)),
 ('out_p

In [175]:
model_weight = {name: param.data for name, param in model.named_parameters()}
Wi = model_weight['in_proj_weight']
Wo = model_weight['out_proj.weight']
Wbi = model_weight['in_proj_bias']
Wbo = model_weight['out_proj.bias']
print(Wi)

tensor([[-0.5808, -0.1098, -0.0357, -0.5751],
        [-0.0407,  0.0463, -0.6055, -0.3367],
        [ 0.0830, -0.4848, -0.0125,  0.0392],
        [-0.2178, -0.2547, -0.5971, -0.3331],
        [ 0.0095, -0.2803, -0.5334,  0.2403],
        [-0.4390,  0.5532, -0.5252,  0.1394],
        [-0.0308, -0.3543, -0.5856, -0.3669],
        [ 0.3372,  0.3948, -0.2288, -0.4667],
        [ 0.4484,  0.5747,  0.4883, -0.0618],
        [ 0.2787,  0.2623,  0.2026,  0.1039],
        [ 0.1447, -0.0516,  0.3138, -0.0649],
        [-0.3639,  0.1680,  0.5810,  0.5685]])


In [181]:
Wi_q, Wi_k, Wi_v = Wi.chunk(3, dim=0)
Wbi_q, Wbi_k, Wbi_v = Wbi.chunk(3, dim=0)
QW = torch.matmul(X.permute(1, 0, 2), Wi_q.T) + Wbi_q
KW = torch.matmul(Y.permute(1, 0, 2), Wi_k.T) + Wbi_k
VW = torch.matmul(Y.permute(1, 0, 2), Wi_v.T) + Wbi_v

print(QW.shape)
print(QW)

KW_t = KW.transpose(-2, -1)
QK_t = torch.bmm(QW, KW_t)
QK_scaled = QK_t / (edim ** 0.5)
attn_weights_ = F.softmax(QK_scaled, dim=-1)

torch.Size([1, 1, 4])
tensor([[[ 1.6785,  0.1756, -0.3511,  0.2078]]])


In [174]:
print(attn_weights_)
print(attn_output_weights)

tensor([[[0.1296, 0.1531, 0.1393, 0.1467, 0.1635, 0.1132, 0.1546]]])
tensor([[[0.1296, 0.1531, 0.1393, 0.1467, 0.1635, 0.1132, 0.1546]]], grad_fn=<MeanBackward1>)


In [39]:
AV = torch.matmul(attn_weights_, VW)
attn_output_ = torch.matmul(AV, Wo.T) + Wbo

In [40]:
print(attn_output_)
print(attn_output)

tensor([[[-0.0625,  0.0904,  0.1305, -0.1482],
         [-0.4081,  0.3104,  0.2189, -0.0764],
         [-0.4028,  0.3015,  0.2174, -0.0791],
         [-0.3206,  0.2504,  0.1944, -0.0949],
         [-0.1308,  0.1265,  0.1498, -0.1374]],

        [[-0.1675,  0.1690,  0.1499, -0.0520],
         [-0.1171,  0.0575,  0.0756, -0.0196],
         [-0.1866,  0.1673,  0.1616, -0.0732],
         [-0.1517,  0.1413,  0.1286, -0.0436],
         [-0.1326,  0.0947,  0.1009, -0.0316]]])
tensor([[[-0.0625,  0.0904,  0.1305, -0.1482],
         [-0.4081,  0.3104,  0.2189, -0.0764],
         [-0.4028,  0.3015,  0.2174, -0.0791],
         [-0.3206,  0.2504,  0.1944, -0.0949],
         [-0.1308,  0.1265,  0.1498, -0.1374]],

        [[-0.1675,  0.1690,  0.1499, -0.0520],
         [-0.1171,  0.0575,  0.0756, -0.0196],
         [-0.1866,  0.1673,  0.1616, -0.0732],
         [-0.1517,  0.1413,  0.1286, -0.0436],
         [-0.1326,  0.0947,  0.1009, -0.0316]]], grad_fn=<TransposeBackward0>)


## nn.Linear

In [41]:
model = nn.Linear(4, 4)
model

Linear(in_features=4, out_features=4, bias=True)

In [42]:
pprint(list(model.named_parameters()))

[('weight',
  Parameter containing:
tensor([[ 0.4057, -0.1641, -0.1456,  0.2699],
        [-0.2218, -0.0159, -0.4409,  0.1662],
        [ 0.3244,  0.2228, -0.1661, -0.1230],
        [-0.1333,  0.3326, -0.3842, -0.0652]], requires_grad=True)),
 ('bias',
  Parameter containing:
tensor([-0.1197,  0.4730,  0.3838, -0.2536], requires_grad=True))]


In [43]:
model_weight = {name: param.data for name, param in model.named_parameters()}
W = model_weight['weight']
B = model_weight['bias']

X = torch.randn(4) 
print(X.shape)
print(X)
output = model(X)
print(output.shape)
print(output)


torch.Size([4])
tensor([-0.3750,  0.0861, -1.5094, -0.3185])
torch.Size([4])
tensor([-0.1522,  1.1674,  0.5712,  0.4257], grad_fn=<ViewBackward0>)


In [44]:
output_ = X.matmul(W.T) + B
print(output_)
print(output)

tensor([-0.1522,  1.1674,  0.5712,  0.4257])
tensor([-0.1522,  1.1674,  0.5712,  0.4257], grad_fn=<ViewBackward0>)


## nn.LayerNorm

参考サイト
https://qiita.com/dl_from_scratch/items/133fe741b67ed14f1856

In [45]:
model = nn.LayerNorm(4)
model

LayerNorm((4,), eps=1e-05, elementwise_affine=True)

In [46]:
pprint(list(model.named_parameters()))

[('weight', Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)),
 ('bias', Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True))]


In [47]:
model_weight = {name: param.data for name, param in model.named_parameters()}
W = model_weight['weight']
B = model_weight['bias']

X = torch.randn(4) 
print(X.shape)
print(X)
output = model(X)
print(output.shape)
print(output)


torch.Size([4])
tensor([ 0.2881, -0.5361,  1.9212, -0.8353])
torch.Size([4])
tensor([ 0.0734, -0.6965,  1.5990, -0.9760], grad_fn=<NativeLayerNormBackward0>)


In [48]:
output_ = X.matmul(W.T) + B
print(output_)
print(output)

tensor([0.8379, 0.8379, 0.8379, 0.8379])
tensor([ 0.0734, -0.6965,  1.5990, -0.9760], grad_fn=<NativeLayerNormBackward0>)


/tmp/ipykernel_168480/3362812588.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3675.)
  output_ = X.matmul(W.T) + B
